name: Docker Compose Action Fror The Frontend

on:
  push: 
    branches: [main]
    # paths:
    #   - "redash/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Create env file"
        run: |
          touch .env
          echo BACKEND_API_URI=${{ secrets.BACKEND_API_URI }} >> .env
          echo REDASH_COOKIE_SECRET=${{ secrets.REDASH_COOKIE_SECRET }} >> .env
          echo REDASH_SECRET_KEY=${{ secrets.REDASH_SECRET_KEY }} >> .env

      - name: Run docker-compose
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./redash/compose.yaml"
          run: |
            docker compose build
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker push

#       #- name: Deploy api to Production
#       #  run: |
#       #    ssh user@your-server "cd /path/to/your/frontend && docker-compose pull && docker-compose up -d"

