name: Docker Compose Action For The Backend

on: 
  push:
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Create env file"
        run: |
          touch .env
          echo API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env

      - name: Run docker-compose
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./api/docker-compose.yml"
          run: |
            docker-compose build
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker-compose push
#       #- name: Deploy api to Production
#       #  run: |
#       #    ssh user@ip "cd /path/to/your/frontend && docker-compose pull && docker-compose up -d"

      
