name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
           compose-file: "./api/docker-compose.yml"
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./api/docker-compose.yml"

      - name: Execute tests in the running services
        run: |
          docker-compose up -d --build
